package declarant

// §2.7 conformance (§5.4 claim 15): golden request bytes, no force_scores
// anywhere in the types, total classification with a fail-closed Unknown,
// and the 500-edge feed consult preceding any decision.

import (
	"context"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"net/http"
	"net/http/httptest"
	"os"
	"path/filepath"
	"reflect"
	"strings"
	"testing"
)

// goldenRequest is the fixed declaration pinned by testdata/request-golden.json.
func goldenRequest() Request {
	return Request{
		EpisodeSeed:      "golden-episode",
		IdempotencyKey:   DeriveKey("per-actor", "run-7", "sample.transfer", []byte(`{"amount":"100.00","unit":"alpha"}`)),
		IntentSpecHash:   strings.Repeat("11", 32),
		IdempotencyScope: "per-actor",
	}
}

func TestGoldenRequestBytes(t *testing.T) {
	golden := filepath.Join("testdata", "request-golden.json")
	got, err := MarshalRequest(goldenRequest())
	if err != nil {
		t.Fatalf("MarshalRequest: %v", err)
	}
	if os.Getenv("DECLARANT_GOLDEN_WRITE") == "1" {
		if err := os.MkdirAll("testdata", 0o755); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(golden, got, 0o644); err != nil {
			t.Fatal(err)
		}
		t.Logf("golden regenerated (%d bytes)", len(got))
	}
	want, err := os.ReadFile(golden)
	if err != nil {
		t.Fatalf("golden missing (%v) - regenerate with DECLARANT_GOLDEN_WRITE=1", err)
	}
	if string(got) != string(want) {
		t.Fatalf("request marshal drifted from the golden bytes:\n got: %s\nwant: %s", got, want)
	}
	// The empty optional passthrough must be OMITTED, not sent blank.
	if strings.Contains(string(got), "rule_artifact_hash") {
		t.Fatalf("empty rule_artifact_hash must be omitted from the wire: %s", got)
	}
}

func TestNoForceScoresInAnyType(t *testing.T) {
	// §2.7: the guarded test affordance is unreachable through the SDK by
	// construction — no field, no tag, in the public or wire type.
	for _, typ := range []reflect.Type{
		reflect.TypeOf(Request{}),
		reflect.TypeOf(wireRequest{}),
	} {
		for i := 0; i < typ.NumField(); i++ {
			f := typ.Field(i)
			if strings.Contains(strings.ToLower(f.Name), "force") ||
				strings.Contains(f.Tag.Get("json"), "force") {
				t.Errorf("%s.%s: force_scores-shaped field in a declarant type", typ.Name(), f.Name)
			}
		}
	}
}

func TestDeriveKeyShape(t *testing.T) {
	args := []byte(`{"a":1}`)
	sum := sha256.Sum256(args)
	want := "scope-x:run-1:tool.name:" + hex.EncodeToString(sum[:])
	if got := DeriveKey("scope-x", "run-1", "tool.name", args); got != want {
		t.Fatalf("DeriveKey = %q, want %q", got, want)
	}
	// Deterministic: same identity, same key — the dedup property.
	if DeriveKey("scope-x", "run-1", "tool.name", args) != want {
		t.Fatal("DeriveKey is not deterministic")
	}
}

func TestIntentIDMatchesGateDerivation(t *testing.T) {
	// Cross-implementation pin: the frozen feed fixture's first intent was
	// generated by the REAL gate from seed "fixture-achieved". Reading the
	// fixture is a byte read, not an import — the tree stays isolated.
	raw, err := os.ReadFile(filepath.Join("..", "core", "contract", "feed", "events-good.jsonl"))
	if err != nil {
		t.Skipf("feed fixture absent (%v) - a skipped fixture test is never a green one", err)
	}
	var first struct {
		IntentID string `json:"intent_id"`
		Detail   string `json:"detail"`
	}
	if err := json.Unmarshal([]byte(strings.SplitN(string(raw), "\n", 2)[0]), &first); err != nil {
		t.Fatalf("parsing fixture line 1: %v", err)
	}
	if got := IntentID("fixture-achieved"); got != first.IntentID {
		t.Fatalf("IntentID(\"fixture-achieved\") = %q, gate produced %q", got, first.IntentID)
	}
	if first.Detail != first.IntentID {
		t.Fatalf("fixture DECLARED detail %q != intent_id %q", first.Detail, first.IntentID)
	}
}

func TestClassificationTotal(t *testing.T) {
	cases := []struct {
		terminal, reason string
		class            Class
		safe             bool
	}{
		{"ACHIEVED", "", Proceed, false},
		{"SHADOW_RECORDED", "", ShadowRecorded, true},
		{"FAILED", "unevaluable:absent-key", SDKBug, true},
		{"FAILED", "unevaluable:unattested-spec", SpecUnattested, true},
		{"FAILED", "unevaluable:invalid-posture", SpecDefect, true},
		{"FAILED", "unevaluable:empty-criteria", SpecDefect, true},
		{"FAILED", "unevaluable:invalid-volatility:alpha", SpecDefect, true},
		{"FAILED", "unevaluable:human-judgment:beta", HumanJudgment, true},
		{"FAILED", "unevaluable:alpha", Unevaluable, true},
		{"FAILED", "revoked:pull-1", Revoked, true},
		{"FAILED", "alpha,beta", PolicyDenied, true},
		{"FAILED_AT_DISPATCH", "volatile-recheck:gamma", FactDrift, true},
		{"FAILED_AT_DISPATCH", "idempotency-collision", AlreadyReserved, false},
		{"FAILED_AT_DISPATCH", "revoked:pull-1", Revoked, true},
		// Outside the closed vocabulary: fail-closed, never a retry.
		{"FAILED", "wat:is-this", Unknown, false},
		{"FAILED", "", Unknown, false},
		{"FAILED_AT_DISPATCH", "novel-cause", Unknown, false},
		{"EXPLODED", "boom", Unknown, false},
	}
	for _, c := range cases {
		class, safe := Classify(c.terminal, c.reason)
		if class != c.class || safe != c.safe {
			t.Errorf("Classify(%q,%q) = (%s,%v), want (%s,%v)", c.terminal, c.reason, class, safe, c.class, c.safe)
		}
	}
}

// gateStub builds an httptest server scripted per path.
func gateStub(t *testing.T, declareStatus int, declareBody string, feedStatus int, feedBody string) (*httptest.Server, *[]string) {
	t.Helper()
	var calls []string
	mux := http.NewServeMux()
	mux.HandleFunc("POST /v2/intents", func(w http.ResponseWriter, r *http.Request) {
		calls = append(calls, "POST /v2/intents")
		w.WriteHeader(declareStatus)
		w.Write([]byte(declareBody))
	})
	mux.HandleFunc("GET /v2/intents/{id}/events", func(w http.ResponseWriter, r *http.Request) {
		calls = append(calls, "GET "+r.URL.Path)
		w.WriteHeader(feedStatus)
		w.Write([]byte(feedBody))
	})
	srv := httptest.NewServer(mux)
	t.Cleanup(srv.Close)
	return srv, &calls
}

func TestDeclareAchieved(t *testing.T) {
	srv, _ := gateStub(t, 200, `{"terminal":"ACHIEVED","reason":"","trajectory_hash":"aa","achieved_seq":7}`, 200, `{}`)
	c := &Client{BaseURL: srv.URL}
	res, err := c.Declare(context.Background(), goldenRequest())
	if err != nil {
		t.Fatal(err)
	}
	if res.Class != Proceed || res.SameKeyRetrySafe || res.Terminal == nil || res.Terminal.AchievedSeq != 7 {
		t.Fatalf("unexpected result: %+v", res)
	}
}

func TestDeclare400IsSDKBug(t *testing.T) {
	srv, _ := gateStub(t, 400, `bad request: json: unknown field "criteria"`, 200, `{}`)
	c := &Client{BaseURL: srv.URL}
	res, err := c.Declare(context.Background(), goldenRequest())
	if err != nil {
		t.Fatal(err)
	}
	if res.Class != SDKBug || res.Terminal != nil {
		t.Fatalf("unexpected result: %+v", res)
	}
}

func TestDeclare500ConsultsFeedBeforeDeciding(t *testing.T) {
	id := IntentID("golden-episode")
	feed := `{"intent_id":"` + id + `","events":[` +
		`{"seq":1,"intent_seq":0,"intent_id":"` + id + `","type":"DECLARED","detail":"` + id + `"},` +
		`{"seq":2,"intent_seq":1,"intent_id":"` + id + `","type":"ACHIEVED","detail":"` + id + `","idempotency_key":"k","intent_spec_hash":"h","trajectory_hash":"th"}]}`
	srv, calls := gateStub(t, 500, `internal error`, 200, feed)
	c := &Client{BaseURL: srv.URL}
	res, err := c.Declare(context.Background(), goldenRequest())
	if err != nil {
		t.Fatal(err)
	}
	if !res.FeedConsulted || res.Class != Proceed || res.SameKeyRetrySafe {
		t.Fatalf("500 edge must decide from the observed ACHIEVED record: %+v", res)
	}
	want := []string{"POST /v2/intents", "GET /v2/intents/" + id + "/events"}
	if len(*calls) != 2 || (*calls)[0] != want[0] || (*calls)[1] != want[1] {
		t.Fatalf("call order = %v, want %v (the consult PRECEDES the decision)", *calls, want)
	}
}

func TestDeclare500InFlightIsIndeterminate(t *testing.T) {
	id := IntentID("golden-episode")
	// Records exist but no terminal-position hash: the intent is mid-flight
	// or torn — nothing decides.
	feed := `{"intent_id":"` + id + `","events":[{"seq":1,"intent_seq":0,"intent_id":"` + id + `","type":"DECLARED","detail":"` + id + `"}]}`
	srv, _ := gateStub(t, 500, `internal error`, 200, feed)
	c := &Client{BaseURL: srv.URL}
	res, err := c.Declare(context.Background(), goldenRequest())
	if err != nil {
		t.Fatal(err)
	}
	if res.Class != Indeterminate || res.SameKeyRetrySafe || !res.FeedConsulted {
		t.Fatalf("unexpected result: %+v", res)
	}
}

func TestDeclare500FeedUnreachableIsIndeterminate(t *testing.T) {
	srv, _ := gateStub(t, 500, `internal error`, 500, `also down`)
	c := &Client{BaseURL: srv.URL}
	res, err := c.Declare(context.Background(), goldenRequest())
	if err != nil {
		t.Fatal(err)
	}
	if res.Class != Indeterminate || res.FeedConsulted {
		t.Fatalf("an unreachable feed decides NOTHING: %+v", res)
	}
}

func TestPollAchieved(t *testing.T) {
	mux := http.NewServeMux()
	mux.HandleFunc("GET /v2/events", func(w http.ResponseWriter, r *http.Request) {
		if r.URL.Query().Get("since") != "4" || r.URL.Query().Get("type") != "ACHIEVED" {
			t.Errorf("query = %s", r.URL.RawQuery)
		}
		w.Write([]byte(`{"events":[{"seq":9,"intent_seq":6,"intent_id":"aa","type":"ACHIEVED","idempotency_key":"k","trajectory_hash":"th"}],"next_since":9}`))
	})
	srv := httptest.NewServer(mux)
	t.Cleanup(srv.Close)
	c := &Client{BaseURL: srv.URL}
	recs, next, err := c.PollAchieved(context.Background(), 4)
	if err != nil {
		t.Fatal(err)
	}
	if len(recs) != 1 || recs[0].IdempotencyKey != "k" || next != 9 {
		t.Fatalf("recs=%+v next=%d", recs, next)
	}
}
